import { useEffect, useMemo, useRef, useState } from 'react';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Checkbox, Radio } from '../components/Checkbox';
import { Field } from '../components/Field';
import { Icon } from '../components/Icon';
import { Modal } from '../components/Modal';
import { Select } from '../components/Select';
import { SqlEditor } from '../components/SqlEditor';
import { Alert } from '../components/Toast';
import { byteLength, countLines, exportFileName, formatBytes, type ExportFormat } from '../core/files';
import { DEFAULT_GENERATE_OPTIONS, EXPORT_ENGINES, generatorFor, type GenerateOptions } from '../core/generate';
import { generateJson } from '../core/generate/json';
import { plural } from '../core/plural';
import { ENGINES } from '../core/schemaList';
import { timestamp } from '../core/time';
import { findProblems } from '../core/validate';
import { versionLabel } from '../core/versions';
import { useUiStore, type ExportSource } from '../store/ui';
import { copyExport, exportFile } from './exportActions';

const APP_NAME = 'Schema Studio';

type Option = Exclude<keyof GenerateOptions, 'header'>;

const DATABASES = ENGINES.map((engine) => {
  const supported = EXPORT_ENGINES.includes(engine);
  return { value: engine, label: supported ? engine : `${engine} (soon)`, disabled: !supported };
});

export interface ExportDialogProps {
  schema: ExportSource;
}

export function ExportDialog({ schema }: ExportDialogProps) {
  const closeDialog = useUiStore((s) => s.closeDialog);
  const [format, setFormat] = useState<ExportFormat>('sql');
  // DDL is written for an engine that has a generator, whatever the schema was made for.
  const [database, setDatabase] = useState(EXPORT_ENGINES.includes(schema.engine) ? schema.engine : EXPORT_ENGINES[0]);
  const [options, setOptions] = useState<GenerateOptions>(DEFAULT_GENERATE_OPTIONS);
  // The time in the file's header is that of opening the dialog, so the preview does not change under the reader.
  const [openedAt] = useState(Date.now);

  const version = schema.version === null ? 'not saved' : versionLabel(schema.version);
  const text = useMemo(() => {
    if (format === 'json') return generateJson({ name: schema.name, version: schema.version, engine: schema.engine }, schema.tables, options);
    const header = [
      `${schema.name} · ${version}${schema.unsaved ? ' + unsaved changes' : ''} · ${database}`,
      `generated by ${APP_NAME} ${timestamp(openedAt)}`,
    ];
    return generatorFor(database)?.generate(schema.tables, { ...options, header }) ?? '';
  }, [format, database, options, schema, version, openedAt]);

  const fileName = exportFileName(schema.name, schema.version, format);
  const problems = useMemo(() => findProblems(schema.tables).length, [schema.tables]);
  const toggle = (option: Option) => (checked: boolean) => setOptions((current) => ({ ...current, [option]: checked }));
  const save = () => exportFile(fileName, text);

  // ⌘⏎ exports from anywhere in the dialog. The handler is renewed on every render, so it sees the current text.
  const confirm = useRef(save);
  useEffect(() => {
    confirm.current = save;
  });
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Enter' || !(e.metaKey || e.ctrlKey)) return;
      e.preventDefault();
      confirm.current();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  return (
    <Modal
      title="Export Schema"
      subtitle={`${schema.name} · ${version} · ${plural(schema.tables.length, 'table')}${schema.unsaved ? ' · unsaved changes' : ''}`}
      width={860}
      onClose={closeDialog}
      bodyStyle={{ padding: 0 }}
      footerStart={
        <span className="ss-modal-foot-hint">
          <Icon name="file-code" size={14} />
          <span className="ss-mono">{fileName}</span>
          {`· ${formatBytes(byteLength(text))}`}
        </span>
      }
      footer={
        <>
          <Button icon="copy" onClick={() => void copyExport(text)}>
            Copy
          </Button>
          <Button onClick={closeDialog}>Cancel</Button>
          <Button variant="primary" icon="download" kbd={['⌘', '⏎']} onClick={save} data-autofocus>
            Export
          </Button>
        </>
      }
    >
      <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', minHeight: 420 }}>
        <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 16, borderRight: '1px solid var(--line-1)' }}>
          <div>
            <div className="ss-caption" style={{ marginBottom: 8 }}>
              Format
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <Radio
                name="fmt"
                label="SQL"
                description="DDL statements for the target database"
                checked={format === 'sql'}
                onChange={() => setFormat('sql')}
              />
              <Radio
                name="fmt"
                label="JSON"
                description="Schema Studio model, for tooling and CI"
                checked={format === 'json'}
                onChange={() => setFormat('json')}
              />
            </div>
          </div>
          <Field label="Database">
            <Select value={database} onChange={setDatabase} options={DATABASES} disabled={format === 'json'} label="Database" />
          </Field>
          <div>
            <div className="ss-caption" style={{ marginBottom: 8 }}>
              Options
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <Checkbox label="Include indexes" checked={options.indexes} onChange={toggle('indexes')} />
              <Checkbox label="Include foreign keys" checked={options.foreignKeys} onChange={toggle('foreignKeys')} />
              <Checkbox label="Include comments" checked={options.comments} onChange={toggle('comments')} />
              <Checkbox
                label="Add DROP … IF EXISTS"
                checked={options.dropIfExists && format === 'sql'}
                // JSON describes the schema; it has no statements to drop anything.
                disabled={format === 'json'}
                onChange={toggle('dropIfExists')}
              />
            </div>
          </div>
          <div style={{ borderTop: '1px solid var(--line-1)', paddingTop: 14 }}>
            {/* Migrations arrive with the diff engine (roadmap 5.4). */}
            <Checkbox
              label={
                <span className="ss-row" style={{ display: 'inline-flex', gap: 6 }}>
                  Generate migration from previous version
                  <Badge sans>Soon</Badge>
                </span>
              }
              description="ALTER statements between two versions instead of full DDL"
              checked={false}
              disabled
            />
          </div>
        </div>
        <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8, minWidth: 0, background: 'var(--bg-2)' }}>
          <div className="ss-row">
            <span className="ss-caption">Preview</span>
            <span className="ss-spacer" />
            <span className="ss-faint" style={{ fontSize: 12 }}>
              {plural(countLines(text), 'line')}
            </span>
          </div>
          {problems > 0 && (
            <Alert tone="warn" title={`${plural(problems, 'column')} with validation errors`}>
              The exported file may not run until they are fixed. Errors are marked in the inspector.
            </Alert>
          )}
          <SqlEditor value={text} readOnly height={problems > 0 ? 300 : 372} language={format} label="Export preview" />
        </div>
      </div>
    </Modal>
  );
}
