import { useEffect, useMemo, useRef, useState } from 'react';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Checkbox, Radio } from '../components/Checkbox';
import { Field } from '../components/Field';
import { Icon } from '../components/Icon';
import { Modal } from '../components/Modal';
import { Select } from '../components/Select';
import { SqlEditor } from '../components/SqlEditor';
import { Alert } from '../components/Toast';
import { byteLength, countLines, exportFileName, formatBytes, migrationFileName, type ExportFormat } from '../core/files';
import { DEFAULT_GENERATE_OPTIONS, EXPORT_ENGINES, generatorFor, migratorFor, type GenerateOptions } from '../core/generate';
import { generateJson } from '../core/generate/json';
import { plural } from '../core/plural';
import { ENGINES } from '../core/schemaList';
import { timestamp } from '../core/time';
import { findProblems } from '../core/validate';
import { versionLabel } from '../core/versions';
import { useVersions } from '../db/useSchemas';
import { useUiStore, type ExportSource } from '../store/ui';
import { copyExport, exportFile } from './exportActions';

const APP_NAME = 'Schema Studio';

type Option = Exclude<keyof GenerateOptions, 'header'>;

/** How many destructive changes the warning spells out before it only counts the rest. */
const SPELLED_OUT = 2;

const DATABASES = ENGINES.map((engine) => {
  const supported = EXPORT_ENGINES.includes(engine);
  return { value: engine, label: supported ? engine : `${engine} (soon)`, disabled: !supported };
});

export interface ExportDialogProps {
  schema: ExportSource;
}

export function ExportDialog({ schema }: ExportDialogProps) {
  const closeDialog = useUiStore((s) => s.closeDialog);
  const [format, setFormat] = useState<ExportFormat>('sql');
  // DDL is written for an engine that has a generator, whatever the schema was made for.
  const [database, setDatabase] = useState(EXPORT_ENGINES.includes(schema.engine) ? schema.engine : EXPORT_ENGINES[0]);
  const [options, setOptions] = useState<GenerateOptions>(DEFAULT_GENERATE_OPTIONS);
  // The time in the file's header is that of opening the dialog, so the preview does not change under the reader.
  const [openedAt] = useState(Date.now);

  // A migration starts from a saved version: any but the one being exported, unless that has unsaved changes on top.
  const stored = useVersions(schema.id);
  const bases = useMemo(
    () => (stored ?? []).filter((v) => schema.unsaved || v.version !== schema.version),
    [stored, schema.unsaved, schema.version],
  );
  const [wantsMigration, setWantsMigration] = useState(schema.migrateFrom !== undefined);
  const [pickedBase, setPickedBase] = useState(schema.migrateFrom ?? null);
  // Without a pick the migration starts from the version before the exported one.
  const base =
    bases.find((v) => v.version === pickedBase) ?? bases.find((v) => v.version <= (schema.version ?? 0)) ?? bases[0] ?? null;
  const canMigrate = format === 'sql' && base !== null && migratorFor(database) !== null;
  const migrating = wantsMigration && canMigrate;

  const version = schema.version === null ? 'not saved' : versionLabel(schema.version);
  const target = `${version}${schema.unsaved ? ' + unsaved changes' : ''}`;
  const migration = useMemo(() => {
    if (!migrating || !base) return null;
    const header = [
      `${schema.name} · migration ${versionLabel(base.version)} → ${target} · ${database}`,
      `generated by ${APP_NAME} ${timestamp(openedAt)}`,
    ];
    return migratorFor(database)?.migrate(base.snapshot.tables, schema.tables, { header }) ?? null;
  }, [migrating, base, schema, target, database, openedAt]);
  const text = useMemo(() => {
    if (migration) return migration.sql;
    if (format === 'json') return generateJson({ name: schema.name, version: schema.version, engine: schema.engine }, schema.tables, options);
    const header = [`${schema.name} · ${target} · ${database}`, `generated by ${APP_NAME} ${timestamp(openedAt)}`];
    return generatorFor(database)?.generate(schema.tables, { ...options, header }) ?? '';
  }, [migration, format, database, options, schema, target, openedAt]);

  const fileName =
    migration && base
      ? migrationFileName(schema.name, base.version, schema.unsaved ? null : schema.version)
      : exportFileName(schema.name, schema.version, format);
  const destructive = migration?.destructive ?? [];
  const problems = useMemo(() => findProblems(schema.tables).length, [schema.tables]);
  const toggle = (option: Option) => (checked: boolean) => setOptions((current) => ({ ...current, [option]: checked }));
  const save = () => exportFile(fileName, text);

  // ⌘⏎ exports from anywhere in the dialog. The handler is renewed on every render, so it sees the current text.
  const confirm = useRef(save);
  useEffect(() => {
    confirm.current = save;
  });
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Enter' || !(e.metaKey || e.ctrlKey)) return;
      e.preventDefault();
      confirm.current();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  return (
    <Modal
      title="Export Schema"
      subtitle={`${schema.name} · ${version} · ${plural(schema.tables.length, 'table')}${schema.unsaved ? ' · unsaved changes' : ''}`}
      width={860}
      onClose={closeDialog}
      bodyStyle={{ padding: 0 }}
      footerStart={
        <span className="ss-modal-foot-hint">
          <Icon name="file-code" size={14} />
          <span className="ss-mono">{fileName}</span>
          {`· ${formatBytes(byteLength(text))}`}
        </span>
      }
      footer={
        <>
          <Button icon="copy" onClick={() => void copyExport(text)}>
            Copy
          </Button>
          <Button onClick={closeDialog}>Cancel</Button>
          <Button variant="primary" icon="download" kbd={['⌘', '⏎']} onClick={save} data-autofocus>
            Export
          </Button>
        </>
      }
    >
      <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', minHeight: 420 }}>
        <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 16, borderRight: '1px solid var(--line-1)' }}>
          <div>
            <div className="ss-caption" style={{ marginBottom: 8 }}>
              Format
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <Radio
                name="fmt"
                label="SQL"
                description="DDL statements for the target database"
                checked={format === 'sql'}
                onChange={() => setFormat('sql')}
              />
              <Radio
                name="fmt"
                label="JSON"
                description="Schema Studio model, for tooling and CI"
                checked={format === 'json'}
                onChange={() => setFormat('json')}
              />
            </div>
          </div>
          <Field label="Database">
            <Select value={database} onChange={setDatabase} options={DATABASES} disabled={format === 'json'} label="Database" />
          </Field>
          <div>
            <div className="ss-caption" style={{ marginBottom: 8 }}>
              Options
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {/* A migration is everything that changed: there is nothing to leave out of it. */}
              <Checkbox label="Include indexes" checked={options.indexes} disabled={migrating} onChange={toggle('indexes')} />
              <Checkbox label="Include foreign keys" checked={options.foreignKeys} disabled={migrating} onChange={toggle('foreignKeys')} />
              <Checkbox label="Include comments" checked={options.comments} disabled={migrating} onChange={toggle('comments')} />
              <Checkbox
                label="Add DROP … IF EXISTS"
                checked={options.dropIfExists && format === 'sql' && !migrating}
                // JSON describes the schema; it has no statements to drop anything.
                disabled={format === 'json' || migrating}
                onChange={toggle('dropIfExists')}
              />
            </div>
          </div>
          <div style={{ borderTop: '1px solid var(--line-1)', paddingTop: 14 }}>
            <Checkbox
              label="Generate migration from previous version"
              description={
                base
                  ? `ALTER statements from ${versionLabel(base.version)} to ${version} instead of full DDL`
                  : 'ALTER statements between two versions instead of full DDL'
              }
              checked={migrating}
              // It takes an earlier saved version to start from, and SQL to write.
              disabled={!canMigrate}
              onChange={setWantsMigration}
            />
            {migrating && base && (
              <div className="ss-row" style={{ marginTop: 10, paddingLeft: 22 }}>
                <Select
                  size="sm"
                  mono
                  value={String(base.version)}
                  onChange={(v) => setPickedBase(Number(v))}
                  options={bases.map((v) => ({ value: String(v.version), label: versionLabel(v.version) }))}
                  label="Base version"
                  style={{ width: 72 }}
                />
                <Icon name="arrow-right" size={14} style={{ color: 'var(--ink-3)' }} />
                <Badge tone="accent">{version}</Badge>
                {schema.unsaved && <Badge tone="modified">unsaved</Badge>}
              </div>
            )}
          </div>
        </div>
        <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8, minWidth: 0, background: 'var(--bg-2)' }}>
          <div className="ss-row">
            <span className="ss-caption">Preview</span>
            <span className="ss-spacer" />
            {migration ? (
              <Badge tone="modified" sans>
                {plural(migration.statements, 'statement')}
              </Badge>
            ) : (
              <span className="ss-faint" style={{ fontSize: 12 }}>
                {plural(countLines(text), 'line')}
              </span>
            )}
          </div>
          {problems > 0 && (
            <Alert tone="warn" title={`${plural(problems, 'column')} with validation errors`}>
              The exported file may not run until they are fixed. Errors are marked in the inspector.
            </Alert>
          )}
          {destructive.length > 0 && (
            <Alert tone="warn" title={plural(destructive.length, 'destructive change')}>
              {destructive
                .slice(0, SPELLED_OUT)
                .map((d) => d.message)
                .join(' ')}
              {destructive.length > SPELLED_OUT ? ` And ${destructive.length - SPELLED_OUT} more.` : ''}
            </Alert>
          )}
          <SqlEditor
            value={text}
            readOnly
            // The preview gives up the height of the warnings above it.
            height={372 - (problems > 0 ? 72 : 0) - (destructive.length > 0 ? 72 : 0)}
            language={format}
            label="Export preview"
          />
        </div>
      </div>
    </Modal>
  );
}
