import { describe, expect, it } from 'vitest';
import { ecommerceTables } from '../fixtures/ecommerce';
import { ecommerceMysqlDump, ecommercePhpMyAdmin } from '../fixtures/sql';
import type { Table } from '../model';
import { mysqlParser } from '../parse/mysql';
import { EXPORT_ENGINES, generatorFor, type GenerateOptions } from './index';
import { mysqlGenerator, quoteName, quoteText } from './mysql';
import { postgresGenerator } from './postgres';

const generate = (tables: readonly Table[], options?: Partial<GenerateOptions>) => mysqlGenerator.generate(tables, options);

function parse(sql: string): Table[] {
  const outcome = mysqlParser.parse(sql);
  if (!outcome.ok) throw new Error(`${outcome.error.message} ${outcome.error.detail ?? ''}\n${sql}`);
  return outcome.tables;
}

/** The ecommerce sample as a MySQL database has it: the tables of its mysqldump script. */
const shop = () => parse(ecommerceMysqlDump);
const named = (...names: string[]) => shop().filter((t) => names.includes(t.name));

describe('generate', () => {
  it('writes a table with its comments inside it, then its indexes', () => {
    expect(generate(named('users'))).toBe(`CREATE TABLE \`users\` (
  \`id\`          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  \`email\`       VARCHAR(255) NOT NULL COMMENT 'Lower-cased; it''s the login.',
  \`name\`        VARCHAR(255),
  \`avatar_url\`  TEXT,
  \`created_at\`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT = 'Registered customers. One row per account.';

CREATE UNIQUE INDEX \`users_email_unique\`
  ON \`users\` (\`email\`);

CREATE INDEX \`users_created_at_idx\`
  ON \`users\` (\`created_at\`);
`);
  });

  it('writes the foreign keys after every table, so the order of the tables does not matter', () => {
    const sql = generate(shop());
    expect(sql).toContain(`ALTER TABLE \`orders\`
  ADD CONSTRAINT \`orders_user_id_fkey\`
  FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`)
  ON DELETE CASCADE;
`);
    expect(sql.indexOf('ALTER TABLE')).toBeGreaterThan(sql.lastIndexOf('CREATE'));
    expect(sql.match(/^ALTER TABLE/gm)).toHaveLength(4);
  });

  it('puts the header on top as comments', () => {
    const sql = generate(named('users'), { header: ['shop · v3 · MySQL', 'generated by Schema Studio'] });
    expect(sql.startsWith('-- shop · v3 · MySQL\n-- generated by Schema Studio\n\nCREATE TABLE `users` (')).toBe(true);
  });

  it('is empty for a schema without tables and no header', () => {
    expect(generate([])).toBe('');
    expect(generate([], { header: ['blank'], dropIfExists: true })).toBe('-- blank\n');
  });

  it('says that it leaves out a table without columns, which MySQL cannot create', () => {
    expect(generate([{ name: 'blank', columns: [] }])).toBe('-- Table blank was left out: MySQL cannot create a table without columns.\n');
  });

  it('gives its blocks the keys the PostgreSQL script has, so the two line up', () => {
    const keys = (blocks: { key: string }[]) => blocks.map((b) => b.key);
    expect(keys(mysqlGenerator.blocks(ecommerceTables))).toEqual(keys(postgresGenerator.blocks(ecommerceTables)));
  });
});

describe('options', () => {
  it('leaves out the indexes, keeping a unique column unique', () => {
    const sql = generate(named('users'), { indexes: false });
    expect(sql).not.toContain('INDEX');
    expect(sql).toContain('  `created_at`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  UNIQUE KEY `users_email_key` (`email`)\n)');
  });

  it('leaves out the foreign keys', () => {
    expect(generate(shop(), { foreignKeys: false })).not.toMatch(/ALTER TABLE|REFERENCES/);
  });

  it('leaves out the comments', () => {
    const sql = generate(shop(), { comments: false });
    expect(sql).not.toContain('COMMENT');
    expect(sql).toContain('  `email`       VARCHAR(255) NOT NULL,');
  });

  it('adds DROP TABLE IF EXISTS before each table, and does not check foreign keys meanwhile', () => {
    const sql = generate(shop(), { dropIfExists: true, header: ['shop'] });
    expect(sql.startsWith('-- shop\n\nSET FOREIGN_KEY_CHECKS = 0;\n\nDROP TABLE IF EXISTS `users`;\nCREATE TABLE `users` (')).toBe(true);
    expect(sql.endsWith('  ON DELETE RESTRICT;\n\nSET FOREIGN_KEY_CHECKS = 1;\n')).toBe(true);
    expect(sql.match(/^DROP TABLE IF EXISTS `\w+`;$/gm)).toHaveLength(5);
    expect(generate(shop())).not.toMatch(/DROP|FOREIGN_KEY_CHECKS/);
  });
});

describe('keys and indexes', () => {
  const table = (columns: Table['columns'], indexes: Table['indexes'] = []): Table => ({ name: 't', columns, indexes });

  it('writes a composite primary key on its own line, in the order of its index', () => {
    const sql = generate([
      table(
        [
          { name: 'a', type: 'INT', pk: true },
          { name: 'b', type: 'INT', pk: true },
        ],
        [{ name: 't_pkey', type: 'PRIMARY KEY', using: 'btree', columns: ['b', 'a'] }],
      ),
    ]);
    expect(sql).toBe('CREATE TABLE `t` (\n  `a`  INT NOT NULL,\n  `b`  INT NOT NULL,\n  PRIMARY KEY (`b`, `a`)\n);\n');
  });

  it('does not name a primary key, which MySQL always calls PRIMARY', () => {
    const sql = generate([table([{ name: 'id', type: 'INT', pk: true }], [{ name: 't_pk', type: 'PRIMARY KEY', using: 'btree', columns: ['id'] }])]);
    expect(sql).toBe('CREATE TABLE `t` (\n  `id`  INT PRIMARY KEY\n);\n');
  });

  it('gives a unique column without an index a key named after the table and the column', () => {
    const sql = generate([
      table([
        { name: 'id', type: 'INT', pk: true },
        { name: 'phone', type: 'VARCHAR(20)', nullable: true, unique: true },
      ]),
    ]);
    expect(sql).toBe('CREATE TABLE `t` (\n  `id`     INT PRIMARY KEY,\n  `phone`  VARCHAR(20),\n  UNIQUE KEY `t_phone_key` (`phone`)\n);\n');
  });

  it('writes a full-text or spatial index as that kind of index, and a hash after its columns', () => {
    const sql = generate([
      table(
        [
          { name: 'a', type: 'INT' },
          { name: 'body', type: 'TEXT' },
          { name: 'place', type: 'POINT' },
        ],
        [
          { name: 't_body_ft', type: 'INDEX', using: 'fulltext', columns: ['body'] },
          { name: 't_place_idx', type: 'INDEX', using: 'spatial', columns: ['place'] },
          { name: 't_a_hash', type: 'INDEX', using: 'hash', columns: ['a'] },
          { name: 't_a_body_key', type: 'UNIQUE', using: 'btree', columns: ['a', 'body'] },
        ],
      ),
    ]);
    expect(sql).toContain('CREATE FULLTEXT INDEX `t_body_ft`\n  ON `t` (`body`);');
    expect(sql).toContain('CREATE SPATIAL INDEX `t_place_idx`\n  ON `t` (`place`);');
    expect(sql).toContain('CREATE INDEX `t_a_hash`\n  ON `t` (`a`) USING HASH;');
    expect(sql).toContain('CREATE UNIQUE INDEX `t_a_body_key`\n  ON `t` (`a`, `body`);');
  });

  it('writes an index of a method MySQL does not have as a btree, and says so', () => {
    const sql = generate([table([{ name: 'tags', type: 'JSON' }], [{ name: 't_tags_idx', type: 'INDEX', using: 'gin', columns: ['tags'] }])]);
    expect(sql).toContain('CREATE INDEX `t_tags_idx`\n  ON `t` (`tags`);\n\n-- Index t_tags_idx uses gin, which MySQL does not have: it was written as a btree index.\n');
  });

  it('says in a comment which index or foreign key it could not write', () => {
    const sql = generate([
      table(
        [
          { name: 'id', type: 'INT', pk: true },
          { name: 'owner', type: 'INT', fk: { table: 'people', column: 'id' } },
          { name: 'parent', type: 'INT', fk: { table: 't', column: 'id' } },
        ],
        [{ name: 't_mail_idx', type: 'INDEX', using: 'btree', columns: ['mail'] }],
      ),
    ]);
    expect(sql).toContain('-- Index t_mail_idx was left out: column mail does not exist in t.');
    expect(sql).toContain('-- Foreign key t.owner was left out: people does not exist.');
    // Without an action the app shows RESTRICT.
    expect(sql).toContain('FOREIGN KEY (`parent`) REFERENCES `t` (`id`)\n  ON DELETE RESTRICT;');
  });

  it('names the database of a table that is in another one', () => {
    expect(generate([{ name: 'log', schema: 'audit', columns: [{ name: 'id', type: 'INT', pk: true }] }])).toContain('CREATE TABLE `audit`.`log` (');
  });
});

describe('quoting', () => {
  it('puts every name in backticks, so that no name is read as a keyword', () => {
    expect(quoteName('order_items')).toBe('`order_items`');
    expect(quoteName('order')).toBe('`order`');
    expect(quoteName('Full Name')).toBe('`Full Name`');
    expect(quoteName('a`b')).toBe('`a``b`');
  });

  it('doubles the quote and the backslash inside a text', () => {
    expect(quoteText("It's a C:\\path.")).toBe("'It''s a C:\\\\path.'");
    const sql = generate([{ name: 't', comment: "It's a table.", columns: [{ name: 'a', type: 'INT', comment: 'The \\ of "a".' }] }]);
    expect(sql).toContain("  `a`  INT NOT NULL COMMENT 'The \\\\ of \"a\".'\n) COMMENT = 'It''s a table.';");
  });
});

describe('round trip', () => {
  it('generates the DDL it parsed, for a mysqldump script and a phpMyAdmin export', () => {
    for (const sql of [ecommerceMysqlDump, ecommercePhpMyAdmin]) {
      const tables = parse(sql);
      expect(parse(generate(tables))).toEqual(tables);
      expect(generate(parse(generate(tables)))).toBe(generate(tables));
    }
  });

  it('holds with DROP TABLE IF EXISTS and a header added', () => {
    expect(parse(generate(shop(), { dropIfExists: true, header: ['shop; v1', "it's a header"] }))).toEqual(shop());
  });

  it('parses the generated DDL of the ecommerce sample back into the sample', () => {
    expect(parse(generate(ecommerceTables))).toEqual(ecommerceTables);
  });

  it('holds for names that need quotes, other databases, composite keys, comments and defaults', () => {
    const tables = parse(`
      CREATE TABLE audit.\`Order Log\` (
        \`order\` bigint, \`user\` varchar(40) DEFAULT 'it''s' COMMENT 'The login; a \\\\ too.', at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        PRIMARY KEY (\`order\`, \`user\`)
      ) COMMENT='Who ordered; and ''when''.';
      CREATE TABLE notes (id int unsigned AUTO_INCREMENT PRIMARY KEY, body varchar(200) UNIQUE, author int unsigned, FOREIGN KEY (author) REFERENCES notes (id) ON DELETE SET NULL);
      CREATE UNIQUE INDEX notes_pair ON notes (body, author);
      CREATE INDEX notes_body_hash ON notes (body) USING HASH;
    `);
    expect(tables.map((t) => t.name)).toEqual(['Order Log', 'notes']);
    expect(parse(generate(tables))).toEqual(tables);
  });

  it('loses only what an option leaves out', () => {
    const parsed = parse(generate(shop(), { indexes: false, foreignKeys: false, comments: false }));
    const columns = (tables: Table[]) => tables.map((t) => t.columns.map((c) => [c.name, c.type, c.nullable, c.pk, c.unique, c.default]));
    expect(columns(parsed)).toEqual(columns(shop()));
    expect(parsed.every((t) => t.comment === '' && t.columns.every((c) => !c.fk && !c.comment))).toBe(true);
    // The keys stay, the unique one under the name it is given without its index.
    expect(parsed[0].indexes?.map((i) => i.name)).toEqual(['users_pkey', 'users_email_key']);
  });
});

describe('generatorFor', () => {
  it('gives the generator of an engine and none for the engines that cannot be exported yet', () => {
    expect(generatorFor('MySQL')).toBe(mysqlGenerator);
    expect(generatorFor('PostgreSQL')).toBe(postgresGenerator);
    expect(generatorFor('SQLite')).toBeNull();
    expect(EXPORT_ENGINES).toEqual(['PostgreSQL', 'MySQL']);
  });
});
