import { describe, expect, it } from 'vitest';
import { ecommerceTables } from '../fixtures/ecommerce';
import { ecommerceDump, ecommerceSql } from '../fixtures/sql';
import { ecommerceSnapshot, tableNamed } from '../fixtures/testing';
import type { Table } from '../model';
import { postgresParser } from '../parse/postgres';
import { generatorFor, EXPORT_ENGINES, type GenerateOptions } from './index';
import { postgresGenerator, quoteName } from './postgres';

const generate = (tables: readonly Table[], options?: Partial<GenerateOptions>) => postgresGenerator.generate(tables, options);

function parse(sql: string): Table[] {
  const outcome = postgresParser.parse(sql);
  if (!outcome.ok) throw new Error(`${outcome.error.message} ${outcome.error.detail ?? ''}\n${sql}`);
  return outcome.tables;
}

const sample = () => ecommerceSnapshot().tables;
const users = () => [tableNamed(ecommerceSnapshot(), 'users')];

describe('generate', () => {
  it('writes a table as in the design: aligned columns, its comment, then its indexes', () => {
    expect(generate(users())).toBe(`CREATE TABLE users (
  id          BIGSERIAL PRIMARY KEY,
  email       VARCHAR(255) NOT NULL,
  name        VARCHAR(255),
  avatar_url  TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE users IS 'Registered customers. One row per account.';

CREATE UNIQUE INDEX users_email_unique
  ON users (email);

CREATE INDEX users_created_at_idx
  ON users (created_at);
`);
  });

  it('writes the foreign keys after every table, so the order of the tables does not matter', () => {
    const sql = generate(sample());
    expect(sql).toContain(`ALTER TABLE orders
  ADD CONSTRAINT orders_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users (id)
  ON DELETE CASCADE;
`);
    // order_items references products, which comes after it.
    expect(sql.indexOf('CREATE TABLE products')).toBeGreaterThan(sql.indexOf('CREATE TABLE order_items'));
    expect(sql.indexOf('ALTER TABLE')).toBeGreaterThan(sql.lastIndexOf('CREATE'));
    expect(sql.match(/^ALTER TABLE/gm)).toHaveLength(4);
  });

  it('puts the header on top as comments', () => {
    const sql = generate(users(), { header: ['ecommerce · v12 · PostgreSQL', 'generated by Schema Studio'] });
    expect(sql.startsWith('-- ecommerce · v12 · PostgreSQL\n-- generated by Schema Studio\n\nCREATE TABLE users (')).toBe(true);
  });

  it('is empty for a schema without tables and no header', () => {
    expect(generate([])).toBe('');
    expect(generate([], { header: ['blank'] })).toBe('-- blank\n');
  });

  it('writes a table without columns', () => {
    expect(generate([{ name: 'blank', columns: [] }])).toBe('CREATE TABLE blank ();\n');
  });
});

describe('options', () => {
  it('leaves out the indexes, keeping a unique column unique', () => {
    const sql = generate(users(), { indexes: false });
    expect(sql).not.toContain('INDEX');
    expect(sql).toContain('  email       VARCHAR(255) NOT NULL UNIQUE,');
    expect(sql).toContain('  id          BIGSERIAL PRIMARY KEY,');
  });

  it('leaves out the foreign keys', () => {
    expect(generate(sample(), { foreignKeys: false })).not.toMatch(/ALTER TABLE|REFERENCES/);
  });

  it('leaves out the comments', () => {
    expect(generate(sample(), { comments: false })).not.toContain('COMMENT ON');
  });

  it('adds DROP TABLE IF EXISTS before each table', () => {
    const sql = generate(sample(), { dropIfExists: true });
    expect(sql).toContain('DROP TABLE IF EXISTS orders CASCADE;\nCREATE TABLE orders (');
    expect(sql.match(/^DROP TABLE IF EXISTS \w+ CASCADE;$/gm)).toHaveLength(5);
    expect(generate(sample())).not.toContain('DROP');
  });
});

describe('keys and constraints', () => {
  const table = (columns: Table['columns'], indexes: Table['indexes'] = []): Table => ({ name: 't', columns, indexes });

  it('writes a composite primary key as a table constraint, in the order of its index', () => {
    const sql = generate([
      table(
        [
          { name: 'a', type: 'INT', pk: true },
          { name: 'b', type: 'INT', pk: true },
        ],
        [{ name: 't_pkey', type: 'PRIMARY KEY', using: 'btree', columns: ['b', 'a'] }],
      ),
    ]);
    expect(sql).toBe('CREATE TABLE t (\n  a  INT NOT NULL,\n  b  INT NOT NULL,\n  PRIMARY KEY (b, a)\n);\n');
  });

  it('names a primary key that has a name of its own', () => {
    const sql = generate([table([{ name: 'id', type: 'INT', pk: true }], [{ name: 't_pk', type: 'PRIMARY KEY', using: 'btree', columns: ['id'] }])]);
    expect(sql).toBe('CREATE TABLE t (\n  id  INT NOT NULL,\n  CONSTRAINT t_pk PRIMARY KEY (id)\n);\n');
  });

  it('goes by the flags of the columns when the indexes no longer match them', () => {
    const sql = generate([
      table(
        [
          { name: 'id', type: 'INT', nullable: false },
          { name: 'code', type: 'TEXT', pk: true },
          { name: 'email', type: 'TEXT', nullable: true },
          { name: 'phone', type: 'TEXT', nullable: true, unique: true },
        ],
        [
          { name: 't_pkey', type: 'PRIMARY KEY', using: 'btree', columns: ['id'] },
          { name: 't_email_unique', type: 'UNIQUE', using: 'btree', columns: ['email'] },
        ],
      ),
    ]);
    expect(sql).toBe('CREATE TABLE t (\n  id     INT NOT NULL,\n  code   TEXT PRIMARY KEY,\n  email  TEXT,\n  phone  TEXT UNIQUE\n);\n');
  });

  it('writes the method of an index that is not a btree, and every column of a composite one', () => {
    const sql = generate([
      table(
        [
          { name: 'a', type: 'INT' },
          { name: 'b', type: 'JSONB' },
        ],
        [
          { name: 't_b_idx', type: 'INDEX', using: 'gin', columns: ['b'] },
          { name: 't_a_b_key', type: 'UNIQUE', using: 'btree', columns: ['a', 'b'] },
        ],
      ),
    ]);
    expect(sql).toContain('CREATE INDEX t_b_idx\n  ON t USING gin (b);');
    expect(sql).toContain('CREATE UNIQUE INDEX t_a_b_key\n  ON t (a, b);');
  });

  it('writes an index of a kind only MySQL has as a btree, and says so', () => {
    const sql = generate([table([{ name: 'body', type: 'TEXT' }], [{ name: 't_body_ft', type: 'INDEX', using: 'fulltext', columns: ['body'] }])]);
    expect(sql).toContain(
      'CREATE INDEX t_body_ft\n  ON t (body);\n\n-- Index t_body_ft uses fulltext, which PostgreSQL does not have: it was written as a btree index.\n',
    );
  });

  it('says in a comment which index or foreign key it could not write', () => {
    const sql = generate([
      table(
        [
          { name: 'id', type: 'INT', pk: true },
          { name: 'owner', type: 'INT', fk: { table: 'people', column: 'id' } },
          { name: 'self', type: 'INT', fk: { table: 't', column: 'nope' } },
          { name: 'parent', type: 'INT', fk: { table: 't', column: 'id' } },
        ],
        [{ name: 't_mail_idx', type: 'INDEX', using: 'btree', columns: ['mail'] }],
      ),
    ]);
    expect(sql).toContain('-- Index t_mail_idx was left out: column mail does not exist in t.');
    expect(sql).toContain('-- Foreign key t.owner was left out: people does not exist.\n-- Foreign key t.self was left out: t.nope does not exist.');
    // Without an action the app shows RESTRICT.
    expect(sql).toContain('FOREIGN KEY (parent) REFERENCES t (id)\n  ON DELETE RESTRICT;');
  });

  it('writes column comments and doubles the quotes inside a comment', () => {
    const sql = generate([{ name: 't', comment: "It's a table.", columns: [{ name: 'a', type: 'INT', comment: 'The "a".' }] }]);
    expect(sql).toContain("COMMENT ON TABLE t IS 'It''s a table.';\nCOMMENT ON COLUMN t.a IS 'The \"a\".';");
  });
});

describe('quoteName', () => {
  it('leaves a plain lower-case name as it is', () => {
    expect(quoteName('order_items')).toBe('order_items');
    expect(quoteName('_x9')).toBe('_x9');
  });

  it('quotes reserved words and names that are not plain', () => {
    expect(quoteName('user')).toBe('"user"');
    expect(quoteName('order')).toBe('"order"');
    expect(quoteName('Users')).toBe('"Users"');
    expect(quoteName('full name')).toBe('"full name"');
    expect(quoteName('a"b')).toBe('"a""b"');
    expect(quoteName('')).toBe('""');
  });
});

describe('round trip', () => {
  it('parses the generated DDL of the ecommerce sample back into the sample', () => {
    expect(parse(generate(ecommerceTables))).toEqual(ecommerceTables);
  });

  it('holds with DROP TABLE IF EXISTS and a header added', () => {
    expect(parse(generate(ecommerceTables, { dropIfExists: true, header: ['ecommerce; v1', "it's a header"] }))).toEqual(ecommerceTables);
  });

  it('generates the DDL it parsed, for hand-written DDL and for a pg_dump script', () => {
    for (const sql of [ecommerceSql, ecommerceDump]) {
      const tables = parse(sql);
      expect(parse(generate(tables))).toEqual(tables);
      expect(generate(parse(generate(tables)))).toBe(generate(tables));
    }
  });

  it('holds for names that need quotes, other schemas, composite keys, comments and defaults', () => {
    const tables = parse(`
      CREATE TABLE audit."Order Log" (
        "order" bigint, "user" text DEFAULT 'it''s', at timestamptz DEFAULT now() NOT NULL, tags text[] DEFAULT ARRAY['a', 'b'],
        CONSTRAINT order_log_pk PRIMARY KEY ("order", "user")
      );
      CREATE TABLE notes (id serial PRIMARY KEY, body text UNIQUE, log_order bigint, author int REFERENCES notes (id) ON DELETE SET NULL);
      CREATE TABLE blank ();
      CREATE UNIQUE INDEX notes_pair ON notes (body, log_order);
      CREATE INDEX notes_body_hash ON notes USING hash (body);
      COMMENT ON TABLE audit."Order Log" IS 'Who ordered; and ''when''.';
      COMMENT ON COLUMN audit."Order Log"."user" IS 'The login.';
    `);
    expect(tables.map((t) => t.name)).toEqual(['Order Log', 'notes', 'blank']);
    expect(parse(generate(tables))).toEqual(tables);
  });

  it('loses only what an option leaves out', () => {
    const parsed = parse(generate(ecommerceTables, { indexes: false, foreignKeys: false, comments: false }));
    expect(parsed.map((t) => t.columns.map((c) => [c.name, c.type, c.nullable, c.pk, c.unique, c.default]))).toEqual(
      ecommerceTables.map((t) => t.columns.map((c) => [c.name, c.type, c.nullable, c.pk, c.unique, c.default])),
    );
    expect(parsed.every((t) => t.comment === '' && t.columns.every((c) => !c.fk))).toBe(true);
    // The keys stay, under the names PostgreSQL gives them.
    expect(parsed[0].indexes?.map((i) => i.name)).toEqual(['users_pkey', 'users_email_key']);
  });
});

describe('generatorFor', () => {
  it('gives the PostgreSQL generator, which is the first of the engines that can be exported', () => {
    expect(generatorFor('PostgreSQL')).toBe(postgresGenerator);
    expect(generatorFor('ClickHouse')).toBeNull();
    expect(EXPORT_ENGINES[0]).toBe('PostgreSQL');
  });
});
