import { describe, expect, it } from 'vitest';
import { mysqlCatalog, postgresCatalog } from '../fixtures/catalogs';
import { ecommerceTables } from '../fixtures/ecommerce';
import { ecommerceMysqlDump } from '../fixtures/sql';
import type { Table } from '../model';
import { mysqlParser } from '../parse/mysql';
import { postgresParser } from '../parse/postgres';
import type { PostgresCatalog } from './catalog';
import {
  catalogDdl,
  connectionLabel,
  countTables,
  DEFAULT_PORTS,
  EMPTY_CONNECTION_FORM,
  INTROSPECT_ENGINES,
  toConnection,
  validateConnection,
  type ConnectionForm,
} from './index';

const byName = (tables: readonly Table[]) => [...tables].sort((a, b) => a.name.localeCompare(b.name));

function parsePostgres(sql: string) {
  const outcome = postgresParser.parse(sql);
  if (!outcome.ok) throw new Error(`${outcome.error.message} ${outcome.error.detail ?? ''}`);
  return outcome;
}

function parseMysql(sql: string) {
  const outcome = mysqlParser.parse(sql);
  if (!outcome.ok) throw new Error(`${outcome.error.message} ${outcome.error.detail ?? ''}`);
  return outcome;
}

describe('catalogDdl for PostgreSQL', () => {
  const sql = catalogDdl(postgresCatalog);

  it('writes a table the way pg_dump does: with its schema, its CHECK constraints inside and its comments after', () => {
    expect(sql).toContain(`CREATE TABLE public.orders (
    id bigint DEFAULT nextval('public.orders_id_seq'::regclass) NOT NULL,
    user_id bigint NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    total numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT orders_total_check CHECK ((total >= (0)::numeric))
);

COMMENT ON TABLE public.orders IS 'Customer orders. Totals are stored, not derived.';
`);
    expect(sql).toContain("COMMENT ON COLUMN public.users.email IS 'Lower-cased; it''s the login.';");
  });

  it('writes the keys after the tables, then the indexes, and the foreign keys last', () => {
    const at = (statement: string) => {
      expect(sql).toContain(statement);
      return sql.indexOf(statement);
    };
    expect(sql.lastIndexOf('CREATE TABLE')).toBeLessThan(at('ALTER TABLE ONLY public.users\n    ADD CONSTRAINT users_pkey PRIMARY KEY (id);'));
    expect(at('ADD CONSTRAINT products_sku_unique UNIQUE (sku);')).toBeLessThan(at('CREATE UNIQUE INDEX users_email_unique ON public.users USING btree (email);'));
    expect(sql.lastIndexOf('CREATE INDEX')).toBeLessThan(
      at('ALTER TABLE ONLY public.orders\n    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;'),
    );
  });

  it('quotes the names that need it, and writes identity and generated columns as such', () => {
    expect(sql).toContain(`CREATE TABLE public."Support Tickets" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "order" bigint,`);
    expect(sql).toContain('    subject_length integer GENERATED ALWAYS AS (length((subject)::text)) STORED\n);');
    expect(sql).toContain('ALTER TABLE ONLY public."Support Tickets"\n    ADD CONSTRAINT "Support Tickets_pkey" PRIMARY KEY (id);');
  });

  it('reads back as the ecommerce sample the database was loaded with', () => {
    const { tables } = parsePostgres(sql);
    expect(tables.map((t) => t.name)).toEqual(['users', 'orders', 'products', 'order_items', 'payments', 'Support Tickets', 'order_notes', 'note_flags']);
    // PostgreSQL calls a DECIMAL numeric, says what type a text default is, and lists the indexes of a table by name.
    const expected = ecommerceTables.map((t) => ({
      ...t,
      columns: t.columns.map((c) => ({
        ...c,
        type: c.type.replace('DECIMAL', 'NUMERIC'),
        ...(c.default?.startsWith("'") ? { default: `${c.default}::character varying` } : {}),
        ...(t.name === 'users' && c.name === 'email' ? { comment: "Lower-cased; it's the login." } : {}),
      })),
      indexes: [...(t.indexes ?? [])].sort((a, b) => Number(b.type === 'PRIMARY KEY') - Number(a.type === 'PRIMARY KEY') || a.name.localeCompare(b.name)),
    }));
    expect(byName(tables.slice(0, 5))).toEqual(byName(expected));
  });

  it('imports with the warnings of any script for what the model has no place for', () => {
    const { warnings, skipped, tables } = parsePostgres(sql);
    expect(skipped).toBe(0);
    expect(warnings).toEqual([
      '`Support Tickets.subject_length` is a generated column; its expression was not imported.',
      'Index `tickets_subject_lower_idx` on `Support Tickets` uses an expression and was skipped.',
      'The composite foreign key on `note_flags` (`order_id`, `line`) was skipped.',
      '1 CHECK constraint was not imported.',
      '`note_flags` has no primary key.',
    ]);
    const tickets = tables.find((t) => t.name === 'Support Tickets');
    expect(tickets?.columns.map((c) => [c.name, c.type])).toEqual([
      ['id', 'BIGSERIAL'],
      ['order', 'BIGINT'],
      ['state', 'TICKET_STATE'],
      ['subject', 'VARCHAR(200)'],
      ['tags', 'TEXT[]'],
      ['opened_at', 'TIMESTAMPTZ'],
      ['subject_length', 'INTEGER'],
    ]);
    expect(tickets?.columns[1].fk).toEqual({ table: 'orders', column: 'id', onDelete: 'SET NULL' });
    expect(tickets?.indexes?.find((i) => i.name === 'tickets_tags_idx')?.using).toBe('gin');
  });

  it('writes the tables of another schema with that schema, and nothing for a schema without tables', () => {
    const audit: PostgresCatalog = {
      engine: 'PostgreSQL',
      schema: 'audit',
      tables: [{ name: 'log', comment: null }],
      columns: [
        { table: 'log', name: 'id', type: 'integer', notNull: true, default: "nextval('audit.log_id_seq'::regclass)", identity: '', generated: '', comment: null },
        { table: 'log', name: 'what', type: 'text', notNull: false, default: null, identity: '', generated: '', comment: null },
      ],
      constraints: [{ table: 'log', name: 'log_pkey', kind: 'p', definition: 'PRIMARY KEY (id)' }],
      indexes: [],
    };
    expect(catalogDdl(audit)).toBe(`CREATE TABLE audit.log (
    id integer DEFAULT nextval('audit.log_id_seq'::regclass) NOT NULL,
    what text
);

ALTER TABLE ONLY audit.log
    ADD CONSTRAINT log_pkey PRIMARY KEY (id);
`);
    const [log] = parsePostgres(catalogDdl(audit)).tables;
    expect([log.schema, log.columns[0].type, log.columns[0].pk]).toEqual(['audit', 'SERIAL', true]);
    expect(catalogDdl({ ...audit, tables: [], columns: [], constraints: [] })).toBe('');
  });
});

describe('catalogDdl for MySQL', () => {
  it('is what SHOW CREATE TABLE says of each table, as one script', () => {
    const sql = catalogDdl(mysqlCatalog);
    expect(sql.startsWith('CREATE TABLE `order_items` (\n  `id` bigint unsigned NOT NULL AUTO_INCREMENT,')).toBe(true);
    expect(sql.match(/^CREATE TABLE/gm)).toHaveLength(5);
    expect(sql.endsWith("COMMENT='Registered customers. One row per account.';\n")).toBe(true);
    expect(catalogDdl({ ...mysqlCatalog, tables: [] })).toBe('');
  });

  it('reads back as the tables of the dump the database was loaded with', () => {
    const { tables, warnings, skipped } = parseMysql(catalogDdl(mysqlCatalog));
    expect(tables).toEqual(byName(parseMysql(ecommerceMysqlDump).tables));
    expect(warnings).toEqual(['1 CHECK constraint was not imported.', '1 ON UPDATE clause was not imported.']);
    expect(skipped).toBe(0);
  });
});

describe('countTables', () => {
  it('counts the tables that were read', () => {
    expect(countTables(postgresCatalog)).toBe(8);
    expect(countTables(mysqlCatalog)).toBe(5);
  });
});

describe('the connection form', () => {
  const form = (changes: Partial<ConnectionForm> = {}): ConnectionForm => ({ ...EMPTY_CONNECTION_FORM, database: 'shop', user: 'reader', ...changes });

  it('offers the engines whose databases can be read, each with its port', () => {
    expect(INTROSPECT_ENGINES).toEqual(['PostgreSQL', 'MySQL']);
    expect(DEFAULT_PORTS).toEqual({ PostgreSQL: 5432, MySQL: 3306 });
  });

  it('starts on localhost with everything else to fill in', () => {
    expect(EMPTY_CONNECTION_FORM.host).toBe('localhost');
    expect(validateConnection(EMPTY_CONNECTION_FORM)).toEqual({ database: 'Database name cannot be empty.', user: 'User cannot be empty.' });
  });

  it('has no problem with a filled form, a blank password or a blank port', () => {
    expect(validateConnection(form())).toEqual({});
    expect(validateConnection(form({ port: ' 6543 ', password: 'secret', schema: 'audit', ssl: true }))).toEqual({});
  });

  it('says what is wrong with a field', () => {
    expect(validateConnection(form({ host: '  ' }))).toEqual({ host: 'Host cannot be empty.' });
    for (const port of ['0', '65536', '54a2', '-1', '5432.5']) {
      expect(validateConnection(form({ port }))).toEqual({ port: 'Port must be a number from 1 to 65535.' });
    }
  });

  it('becomes a connection with the port and the schema of the engine filled in', () => {
    expect(toConnection(form({ host: ' db.internal ', password: ' s3cret ' }), 'PostgreSQL')).toEqual({
      engine: 'PostgreSQL',
      host: 'db.internal',
      port: 5432,
      database: 'shop',
      user: 'reader',
      // A password is sent as it is typed.
      password: ' s3cret ',
      schema: 'public',
    });
    expect(toConnection(form({ port: '3307', schema: 'ignored', ssl: true }), 'MySQL')).toEqual({
      engine: 'MySQL',
      host: 'localhost',
      port: 3307,
      database: 'shop',
      user: 'reader',
      password: '',
      ssl: true,
    });
  });

  it('names a database by where it is', () => {
    expect(connectionLabel(toConnection(form(), 'PostgreSQL'))).toBe('shop @ localhost:5432');
    expect(connectionLabel(toConnection(form({ schema: 'audit', port: '6543' }), 'PostgreSQL'))).toBe('shop.audit @ localhost:6543');
    expect(connectionLabel(toConnection(form({ host: '10.0.0.5' }), 'MySQL'))).toBe('shop @ 10.0.0.5:3306');
  });
});
